title = "Custom Boost Gitleaks configuration"

[extend]
useDefault = true

[[rules]]
id = "generic-api-key"

 [[rules.allowlists]]
 description="Do not report on path with mocks"
 paths = [ '''(?i)\Wmocks?\W''' ]
 
 [[rules.allowlists]]
 description="Do not report settings in .Net projects"
 regexTarget = "line"  
 regexes = [ '''(?i)publicKeyToken="[^"]+"''' ]
 paths = [ '''(?i)web\.config''' ]

 [[rules.allowlists]]
 description="Do not report on GUID"
 regexTarget = "match"  
 regexes = [ '''(?i)[^A-F0-9]*[A-F0-9]{8}-[A-F0-9]{4}-[1-8][A-F0-9]{3}-[A-F0-9]{4}-[A-F0-9]{12}[^A-F0-9]*''' ]

 [[rules.allowlists]]
 description="Do not report <key> in XML"
 regexTarget = "line"
 regexes = [ '''(?i)<key[^>]*>[^<]*</key>''' ]
 paths = [ '''(?i)\.xml''' ]
